In [2]:
!pip install -q transformers torch

In [19]:
import pandas as pd

In [3]:
from transformers import pipeline

In [4]:
ner_pipeline = pipeline(        #load a pretrained NER model
    "ner",
    model="dslim/bert-base-NER",
    aggregation_strategy="simple"
)

config.json:   0%|          | 0.00/829 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors: reconstructing file:   0%|          |  0.00B /  433MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dslim/bert-base-NER
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/59.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [9]:
text = "Experience with Python, SQL and AWS."
# Pretrained Transformer NER
results = ner_pipeline(text)

print("Pretrained Transformer NER:")

for entity in results:

    print(
        entity["word"],
        "→",
        entity["entity_group"],
        "| Confidence:",
        round(entity["score"], 3)
    )

Pretrained Transformer NER:
Python → MISC | Confidence: 0.994
SQL → MISC | Confidence: 0.984
AWS → MISC | Confidence: 0.976

In [10]:
text = """
The candidate should have experience with Python,
SQL, AWS, Power BI and Machine Learning.
"""

results = ner_pipeline(text)

for entity in results:
    print(
        entity["word"],
        "→",
        entity["entity_group"],
        "| Score:",
        round(entity["score"], 3)
    )

Python → MISC | Score: 0.995
SQL → MISC | Score: 0.98
AWS → MISC | Score: 0.945
Power BI → MISC | Score: 0.788
Machine Learning → ORG | Score: 0.804

In [14]:
skill_list = [
    "Python",
    "SQL",
    "AWS",
    "Power BI",
    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "Tableau",
    "MySQL",
    "Microsoft Azure"
]

In [15]:
import re

def extract_skills(text, skill_list):

    found_skills = []

    for skill in skill_list:

        pattern = r"\b" + re.escape(skill) + r"\b"

        if re.search(
            pattern,
            text,
            flags=re.IGNORECASE
        ):
            found_skills.append(skill)

    return found_skills

In [16]:
# Custom Skill Extraction

custom_skills = extract_skills(
    text,
    skill_list
)

print("\nCustom Skill Extraction:")

for skill in custom_skills:
    print(skill, "→ SKILL")

Custom Skill Extraction:
Python → SKILL
SQL → SKILL
AWS → SKILL
Power BI → SKILL
Machine Learning → SKILL

In [20]:
comparison = pd.DataFrame({
    "Method": [
        "Pretrained Transformer NER",
        "Custom Skill Extraction"
    ],

    "Result": [
        ", ".join(
            [entity["word"] + " → " + entity["entity_group"]
             for entity in transformer_results]
        ),

        ", ".join(
            [skill + " → SKILL"
             for skill in custom_skills]
        )
    ]
})

comparison

,Method,Result
0,Pretrained Transformer NER,"Python → MISC, SQL → MISC, AWS → MISC"
1,Custom Skill Extraction,"Python → SKILL, SQL → SKILL, AWS → SKILL, Powe..."

In [ ]:
text = """
Experience with Python, SQL, AWS,
Power BI and Machine Learning.
"""

In [ ]:
transformer_results = ner_pipeline(text)

transformer_entities = [
    entity["word"]
    for entity in transformer_results
]

print("Transformer NER:")
print(transformer_entities)

Transformer NER:
['Python', 'SQL', 'AWS', 'Power BI', 'Machine Learning']

In [ ]:
custom_results = extract_skills(
    text,
    skill_list
)

print("\nCustom Skill Model:")
print(custom_results)

Custom Skill Model:
['Python', 'SQL', 'AWS', 'Power BI', 'Machine Learning']

In [ ]:
import pandas as pd
comparison = pd.DataFrame({
    "Method": [
        "Pretrained Transformer NER",
        "Custom Skill Extraction"
    ],

    "Extracted Entities": [
        ", ".join(transformer_entities),
        ", ".join(custom_results)
    ]
})

comparison

                       Method                            Extracted Entities
0  Pretrained Transformer NER  Python, SQL, AWS, Power BI, Machine Learning
1     Custom Skill Extraction  Python, SQL, AWS, Power BI, Machine Learning